{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-cost-exporter.fullname" . }}
  labels:
    {{- include "kube-cost-exporter.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods", "persistentvolumes", "persistentvolumeclaims", "namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes", "pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kube-cost-exporter.fullname" . }}
  labels:
    {{- include "kube-cost-exporter.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kube-cost-exporter.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kube-cost-exporter.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
